# Generated by Django 3.2.4 on 2021-06-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='points',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
